"""quiht-tools: CLI utilities for the quiht Qt .ui -> HTML renderer.

Public API:
    - `generate`: scan a Qt source tree, copy .ui + resources, write .quiht.json.
    - `pack`: bundle a directory (or a freshly generated bundle) into a .quiht.zip.
    - `unpack`: extract a .quiht.zip back into a directory.

The canonical `.quiht.zip` format is a standard ZIP archive whose root contains:
    - `.quiht.json`  (the manifest)
    - `ui/`          (all .ui files)
    - `resources/`   (all resource files, e.g. PNG icons)
    - `translations.json` (optional)
The manifest's `ui`/`resources` values are paths relative to the archive root.
"""

from __future__ import annotations

try:
    from quiht_tools.__version__ import __version__
except ImportError:  # pragma: no cover - version file is generated by hatch-vcs
    __version__ = "0.0.0+unknown"

from quiht_tools.jsongen import generate
from quiht_tools.pack import pack, unpack

__all__ = ["__version__", "generate", "pack", "unpack"]
